name: release 

on:
  workflow_dispatch:
  workflow_call:
  push:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release-linux-windows:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - run: npm run release:linux
      - run: npm run release:windows

  release-mac:
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - run: npm run release:mac

